spring:
  sql:
    init:
      platform: mysql
  datasource:
    username: sfg_prod_user
    url: jdbc:mariadb://localhost:3306/sfg_prod
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    database: mysql